### ISSUE TITLE
installer.sh error: multiqc 1.19 requires jinja2>=3.0.0, but you have jinja2 2.11.3

### ISSUE THREAD

**Issue by kubu4** [HCGB-IGTP/XICRA#47]
When using the `installer.sh` script to download and install external software, I get the following error (I've truncated the entire output to just the section with the error) that multiqc requires jinja2>=3.0.0. Oddly, it looks like that requirement was satisfied, but then was uninstalled.

The error didn't break/interrupt the installation, so I feel like things might be okay. Figured I'd ask here, though.

```bash
Requirement already satisfied: MarkupSafe>=0.23 in /home/sam/programs/mambaforge/envs/XICRA/lib/python3.7/site-packages (from Jinja2<3.0.0,>=2.11.2->MINTmap==2.0a0) (2.0.1)
Installing collected packages: PyYAML, Jinja2, MINTmap
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.1
    Uninstalling PyYAML-6.0.1:
      Successfully uninstalled PyYAML-6.0.1
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.1.3
    Uninstalling Jinja2-3.1.3:
      Successfully uninstalled Jinja2-3.1.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
multiqc 1.19 requires jinja2>=3.0.0, but you have jinja2 2.11.3 which is incompatible.

Successfully installed Jinja2-2.11.3 MINTmap-2.0a0 PyYAML-5.4.1

+++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
Moving files
+++++++++++++++++++++++++++++++++++++++++++++++++++++++ 


+++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
Remove tmp files
+++++++++++++++++++++++++++++++++++++++++++++++++++++++ 


Done...
```

**Comment by kubu4** [comment]
I'll add that the `XICRA config` command shows that everything is `OK`.

**Comment by JFsanchezherrero** [comment]
Hi there,
As I mentioned in other thread (#42) I will have it fixed and updated and let you know
Best regards

**Comment by JFsanchezherrero** [comment]
Hi there,
please read the thread in #42 as I have fixed and updated the package.

Let me know if it works.
Best regards

**Comment by kubu4** [comment]
Apologies for the delay. I finally got back to this.

After updating, following the instructions in #42, I now get the following error when I run `installer.sh`:

```bash
Collecting PyYAML<6.0.0,>=5.3.1 (from MINTmap==2.0a0)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/sam/programs/mambaforge/envs/XICRA_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/sam/programs/mambaforge/envs/XICRA_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sam/programs/mambaforge/envs/XICRA_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-uu1__8yn/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kubu4** [comment]
Got it resolved!

Had to run the following commands (taken from https://github.com/yaml/pyyaml/issues/736) steps first, followed by the `sh installer.sh` command.

Briefly:

```bash
echo 'Cython < 3.0' > /tmp/constraint.txt

PIP_CONSTRAINT=/tmp/constraint.txt pip wheel PyYAML==5.4.1
```

Thanks!!
